const Breeds = [
  'Mix less than Ten Pounds',
  'Mix Eleven to Twenty Four Pounds',
  'Mix Twenty Five to Forty Nine Pounds',
  'Mix Fifty to Seventy Four Pounds',
  'Mix Seventy Five to Ninety Nine Pounds',
  'Mix One Hundred to One Hundred and Forty Nine Pounds',
  'Mix Over One Hundred and Forty Nine Pounds',
  'Abruzzen',
  'Affenpinscher',
  'Afghan Hound',
  'Aidi',
  'Ainu',
  'Airedale Terrier',
  'Akbash',
  'Akita',
  'Akita American',
  'Akita Japanese',
  'Alapha Blue Blood Bull Dog',
  'Alaskan Husky',
  'Alaskan Klee Kai',
  'Alaskan Malamute',
  'American Bandogge',
  'American Bulldog',
  'American Bull Terrier',
  'American Eskimo',
  'American Foxhound',
  'American Hairless Terrier',
  'American Pit Bull Terrier',
  'American Staffordshire Terrier',
  'American Water Spaniel',
  'Anatolian Shepard',
  'Anglo-Francais Tricolor',
  'Appenzell Mountain Dog',
  'Argentine Dog',
  'Ariegeois',
  'Aussiedoodle',
  'Australian Cattle Dog',
  'Australian Kelpie',
  'Australian Shepherd',
  'Australian Silky Terrier',
  'Australian Terrier',
  'Austrain Hound',
  'Austrain Short-Haired Pinscher',
  'Azawakh',
  'Balkan Hound',
  'Barbet',
  'Basenji',
  'Basset Artesien Normand',
  'Basset Bleu De Gascigne',
  'Basset Fauve De Bretagne',
  'Basset Griffon Vendeen',
  'Basset Hound',
  'Bavarian Mountain Hound',
  'Begle',
  'Beagle Harrier',
  'Beaglier',
  'Bearded Collie',
  'Beauceron',
  'Bedlington Terrier',
  'Belgian Griffon',
  'Belgian Malinois',
  'Belgian Sheepdog',
  'Belgian Shepherd Laeenis',
  'Belgian Shepherd Malinois',
  'Belgian Shepherd Tervuren',
  'Belgian Tervuren',
  'Bergamasco',
  'Berger Picard',
  'Bernese Hound',
  'Bernese Mountain Dog',
  'Bichon Avanese',
  'Bichon Frise',
  'Bichpoo',
  'Black &amp; Tan Connhound',
  'Black &amp; Tan Toy Terrier',
  'Black Forest Hound',
  'Black Mouth Cur',
  'Black Russian Terrier',
  'Bloodhound',
  'Bluetick Coonhound',
  'Bolognese',
  'Border Collie',
  'Border Terrier',
  'Borzoi',
  'Bosnian Hound',
  'Boston Terrier',
  'Bouvier Des Flandres',
  'Boxer',
  'Boxer Mix',
  'Boxerdoodle',
  'Boykin Spaniel',
  'Bracco Italiano',
  'Braque Ariegeois',
  'Braque D&#39;Auvergne',
  'Braque Du Bourbonnais',
  'Braque Dupuy',
  'Braque Saint-Germain',
  'Briard',
  'Briquet',
  'Briquet Griffon Vendeen',
  'Brittany Spaniel',
  'Brussels Griffon',
  'Bull Terrier',
  'Bulldog',
  'Bullmastiff',
  'Bull Breed',
  'Cairn Terrier',
  'Cairnoodle',
  'Canaan Dog',
  'Cane Corso Mastiff',
  'Cao Da Serra De Aires',
  'Cao Da Serra De Estrela',
  'Cao Da Serra De Laboreiro',
  'Cao De Castro Laboreiro',
  'Carolina',
  'Catahoula Leopard Dog',
  'Catalan Sheepdog',
  'Caucasian',
  'Cavachon',
  'Cavalier King Charles Spaniel',
  'Cavapoo',
  'Central Asian Ovtcharka',
  'Ceskey Terrier',
  'Cheaspeake Bay Retriever',
  'Cheaspeake Bay Terrier',
  'Chien Francais',
  'Chihuahua',
  'Chinese Chongqing Dog',
  'Chinese Crested',
  'Chinese Foo Dog',
  'Chinese Imperial Ch&#39;in',
  'Chinese Shar-pei',
  'Chinese Temple Dog',
  'Chinook',
  'Chipoo',
  'Chow Chow',
  'Chow Mix',
  'Cirneco Dell Etna',
  'Clumber Spaniel',
  'Cockapoo',
  'Cocker Spaniel',
  'Collie',
  'Corgi',
  'Coton De Tulear',
  'Croatian Sheepdog',
  'Curly Coated Retriever',
  'Czechoslovakian Wolfdog',
  'Dachshund',
  'Dalmatian',
  'Dalmation Mix',
  'Dachsbracke, Montano-Alpine',
  'Dachsbracke, Westphalian',
  'Dandi Dinmont Terrier',
  'Dashshund Miniture',
  'Dashshund Smooth',
  'Dashshund Wire',
  'Deerhound',
  'Doberman Pinscher',
  'Dobi Mix',
  'Dogo Argentino',
  'Dogue De Bordeaux',
  'Doodleman Pinscher',
  'Drentse Patrijshond',
  'Drever',
  'Dunker',
  'Dutch Shepherd',
  'English Bulldog',
  'English Cocker Spaniel',
  'English Coonhound',
  'English Foxhound',
  'English Pointer',
  'English Setter',
  'English Shepherd',
  'English Springer Spaniel',
  'English Toy Spaniel',
  'Entlebucher Mountain Dog',
  'Eskimo Dog',
  'Estrela Mountain',
  'Field Spaniel',
  'Fila Brasileiro',
  'Finnish Hound',
  'Finnish Lapphund',
  'Flat Coated Retriever',
  'Fox Terrier, Smooth',
  'Fox Terrier, Toy',
  'Fox Terrier, Wire',
  'French Bulldog',
  'French Pointer',
  'French Spaniel',
  'Gammel Dansk Honsehund',
  'German Hovawart',
  'German Hunting Terrier',
  'German Long-Haired Pointer',
  'German Pinscher',
  'German Shepherd',
  'German Shepherd Mix',
  'German Shorthaired Pointer',
  'German Spaniel',
  'German Wirehaired Pointer',
  'Glen of Imaal Terrier',
  'Golden Retriever',
  'Goldendoodle',
  'Gordon Setter',
  'Grand Anglo-Francais',
  'Grand Bleu De Gascogne',
  'Grand Gascon Saintongeois',
  'Grand Griffon Vendeen',
  'Great Dane',
  'Great Pyrenees',
  'Great Spitz',
  'Greater Swiss Mountain Dog',
  'Greek Hound',
  'Greenland',
  'Greyhound',
  'Griffon Brabancon',
  'Griffon Fauve De Bretagne',
  'Griffon Nivernais',
  'Grosser Munsterlander',
  'Gull Dong',
  'Hairless Dog',
  'Haldenstover',
  'Hamilton Hound',
  'Harlekinpinscher',
  'Havanese',
  'Heeler',
  'Hokkaidoken',
  'Hovawart',
  'Hunt Terrier',
  'Husky',
  'Husky Siberian',
  'Husky Japnese',
  'Husky Sakhlin',
  'Hygenhund',
  'Ibizan Hound',
  'Iceland Sheepdog',
  'Illyrain Sheepdog',
  'Irish Setter',
  'Irish Terrier',
  'Irish Water Spaniel',
  'Irish Wolfhound',
  'Italian Greyhound',
  'Italian Hound',
  'Italian Spinone',
  'Jack Russell',
  'Japanese Chin',
  'Japanese Spitz',
  'Jindo',
  'Jura Hound',
  'Kai Dog',
  'Karelian Bear Dog',
  'Karst Sheepdog',
  'Keeshond',
  'Kerry Blue Terrier',
  'Kishu Ken',
  'Kleiner Musterlander',
  'Komondor',
  'Kooikerhondje',
  'Kromfohrlander',
  'Kuvasz',
  'Kyushu',
  'Labradoodle',
  'Labrador Retriver',
  'Lab Mix',
  'Maltipoo',
  'Lagotto Romagnolo',
  'Lakeland Terrier',
  'Lancashire Heeler',
  'Landseer',
  'Lapphund',
  'Lapponian Herder',
  'Leonberger',
  'Levesque',
  'Lhasa Apso',
  'Lhasapoo',
  'Little Lion Dog',
  'Lowchen',
  'Lucernese Hound',
  'Lundehund',
  'Magyar Agar',
  'Malshi',
  'Maltese',
  'Maltipom',
  'Manchester Terrier',
  'Manchester Terrier, Toy',
  'Maremma Sheepdog',
  'Mastiff',
  'McNab',
  'Mexican Hairless',
  'Minature American Shepherd',
  'Minature Australian Shepherd',
  'Mini Dachshund',
  'Miniature Bull Terrier',
  'Miniature Pinscher',
  'Miniature Poodle',
  'Morkie',
  'Mountain Cur',
  'Mudi',
  'Munsterlander',
  'Neapolitan Mastiff',
  'New Guinea Singing Dog',
  'Newfoundland',
  'Norfolk Terrier',
  'Norrbottenspets',
  'Norsk Buhund',
  'Norwegian Buhund',
  'Norwegian Elkhound',
  'Norwegian Lundehund',
  'Norwich Terrier',
  'Nova Scotia Buck Tolling Retriever',
  'Olde English Bulldogge',
  'Olde English Sheepdog',
  'Otterhound',
  'Papillion',
  'Papoo',
  'Parson Russell Terrier',
  'Patterdale Terrier',
  'Peek-A-Pom',
  'Pekepoo',
  'Pekingese',
  'Perdiguero De Burgos',
  'Perdiguero Portugues',
  'Peruvian Inca Orchid',
  'Petit Anglo-Francais',
  'Petit Bleu De Gascogne',
  'Petit Griffon Bleu De Gascogne',
  'Petite Basset Griffon',
  'Pharaoh Hound',
  'Picardy Sheepdog',
  'Picardy Spaniel',
  'Pinscher',
  'Pit Bull',
  'Pit Mix',
  'Plott Hound',
  'Podenco Ibicenco',
  'Podengo Portugueso',
  'Pointer',
  'Poitevin',
  'Polish Hound',
  'Polish Lowland Sheepdog',
  'Polish Owczarek Nizinny',
  'Polish Tatra Sheepdog',
  'Pomchi',
  'Pomeranian',
  'Pont-Audemere Spaniel',
  'Poodle, Minature',
  'Poodle, Standard',
  'Poodle, Toy',
  'Porcelaine',
  'Portuguese Podengo',
  'Portuguese Pointer',
  'Portuguese Water Dog',
  'Posavac Hound',
  'Presa Canario',
  'Pudelpointer',
  'Pug',
  'Puggle',
  'Puli',
  'Pumi',
  'Pyrenean Mastiff',
  'Pyrenean Shepherd',
  'Queensland Heeler',
  'Rafeiro Do Alentejo',
  'Rastreador Brasileiro',
  'Rat Terrier',
  'Redbone Coonhound',
  'Redtick Coonhound',
  'Rhodesian Ridgeback',
  'Rottwiler',
  'Rotti Mix',
  'Rough-Coated Bohemain Pointer',
  'Sabueso Espanol',
  'Sain Bernard',
  'Saluki',
  'Samoyed',
  'Sanshu',
  'Sarplaninac',
  'Schapendoes',
  'Schillerstovare',
  'Schipperke',
  'Schnauzer, Giant',
  'Schnauzer, Miniature',
  'Schnauzer, Standard',
  'Schnoodle',
  'Scottish Deerhound',
  'Scottish Terrier',
  'Sealyham Terrier',
  'Shar-Pei',
  'Sheltie',
  'Shetland Sheepdog',
  'Shiba Inu Dogs',
  'Shih Tzu',
  'Shihpoo',
  'Shiloh Shepherd',
  'Siberian Husky',
  'Siberian Mastiff',
  'Silky Terrier',
  'Skye Terrier',
  'Sloughi',
  'Slovak Tchouvatch',
  'Smalandsstovare',
  'Small Continental Spaniel',
  'Small Gray Elk Dog',
  'Small Spitz',
  'Small Swiss Hound',
  'Smooth-Haired Istrian Hound',
  'Smooth-Muzzled Pyrenees Sheepdog',
  'Soft-Coated Griffon',
  'Soft Coated Wheaten Terrier',
  'Somerset Harrier',
  'South African Boerboel',
  'South Russian Ovcharka',
  'Spanish Greyhound',
  'Spinone Italiano',
  'Staby-houn',
  'Staffordshire Bull Terriers',
  'Steinbracke',
  'Stichelhaar',
  'Sussex Spaniel',
  'Swedish Elkhound',
  'Swedish Shepherd',
  'Swedish Vallhund',
  'Swiss Hound',
  'Tamaskan',
  'Tatra Sheepdog',
  'Telomian',
  'Thai Ridgeback',
  'Tibetan Mastiff',
  'Tibetan Spaniel',
  'Tibetan Terrier',
  'Tosa Inu',
  'Toy Terrier',
  'Transylvanian Hound',
  'Treeing Tennessee Brindle',
  'Treeing Walker Coonhound',
  'Trigg Hound',
  'Tyrolean Hound',
  'Valee Sheepdog',
  'Vizsla',
  'Volpino Italiano',
  'Weimaraner',
  'Welsh Corgi, Cardigan',
  'Welsh Corgi, Pembroke',
  'Welsh Springer Spaniel',
  'Welsh Terrier',
  'West Highland White Terrier',
  'Westie',
  'Wetterhoun',
  'Whippet',
  'Wirehaired Pointing Griffon',
  'Wirehaired Styrian Mountain Hound',
  'Wolf Hybrid',
  'Zoloitzcuintli',
  'Yorkiepoo',
  'Yorkshire Terrier',
  'Yugoslavian Mountain Hound',
  'Yugoslavian Tricolor Hound'
];

export default Breeds;
